print("Enter Principle amount to calculate Simple Interest \n")
a=int(input())
print("Enter Rate \n")
b=float(input())
print("Enter Time \n")
c=int (input())
d=float((a*b*c)/100)
print("Simple interest as per your Input Details is \n")
print("Result as per inserted information is ",d,sep="###",end="#Ended ")